language: generic
sudo: required
services: 
  - docker

before_install:
  - docker build -t mosza16/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true mosza16/docker-react npm run test -- --coverage